# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build the apk connect to test cloud"
  lane :testEnv do
    gradle(
      task: "clean assemble",
      build_type: "debug",
	  flavor: "myapp",
      properties: {
        "android.injected.signing.store.file" => ENV["WORKSPACE"] + "/Keystore.jks",
        "android.injected.signing.store.password" => "SUNMIwireless388",
        "android.injected.signing.key.alias" => "SUNMI_Key",
        "android.injected.signing.key.password" => "SUNMIwireless388",
      } )
  end

  lane :googleTestEnv do
    gradle(
      task: "clean assemble",
      build_type: "debug",
	  flavor: "google",
      properties: {
        "android.injected.signing.store.file" => ENV["WORKSPACE"] + "/Keystore.jks",
        "android.injected.signing.store.password" => "SUNMIwireless388",
        "android.injected.signing.key.alias" => "SUNMI_Key",
        "android.injected.signing.key.password" => "SUNMIwireless388",
      } )
  end
  
  lane :uatEnv do
    gradle(
      task: "clean assemble",
      build_type: "uat",
      properties: {
        "android.injected.signing.store.file" => ENV["WORKSPACE"] + "/Keystore.jks",
        "android.injected.signing.store.password" => "SUNMIwireless388",
        "android.injected.signing.key.alias" => "SUNMI_Key",
        "android.injected.signing.key.password" => "SUNMIwireless388",
      } )
  end
  
  lane :releaseEnv do
    gradle(
      task: "clean assemble",
      build_type: "release",
	  flavor: "myapp",
      properties: {
        "android.injected.signing.store.file" => ENV["WORKSPACE"] + "/Keystore.jks",
        "android.injected.signing.store.password" => "SUNMIwireless388",
        "android.injected.signing.key.alias" => "SUNMI_Key",
        "android.injected.signing.key.password" => "SUNMIwireless388",
      } )
  end
  
  lane :googleEnv do
    gradle(
      task: "clean assemble",
      build_type: "release",
	  flavor: "google",
      properties: {
        "android.injected.signing.store.file" => ENV["WORKSPACE"] + "/Keystore.jks",
        "android.injected.signing.store.password" => "SUNMIwireless388",
        "android.injected.signing.key.alias" => "SUNMI_Key",
        "android.injected.signing.key.password" => "SUNMIwireless388",
      } )
  end
end